------------------------------------------------------------------------
-- FACT SALES

INSERT INTO FACT_SALES (SK_CAR, SK_CLIENT, SK_MANAGER, SK_SALES_DATE, SK_SHOW_ROOM, PRICE)
VALUES
(8, 2, 8, 1, 1, 10000);

INSERT INTO FACT_SALES (SK_CAR, SK_CLIENT, SK_MANAGER, SK_SALES_DATE, SK_SHOW_ROOM, PRICE)
VALUES
(9, 4, 9, 3, 3, 22000);

INSERT INTO FACT_SALES (SK_CAR, SK_CLIENT, SK_MANAGER, SK_SALES_DATE, SK_SHOW_ROOM, PRICE)
VALUES
(10, 8, 10, 4, 4, 500000);


------------------------------------------------------------------------
-- FACT STORAGE SNAPSHOT 

INSERT INTO FACT_STORAGE_SNAPSHOT (SK_CAR, SK_STORAGE, SK_SNAPSHOT_DATE, DAYS_ON_STORAGE)
VALUES
(8, 3, 1, 10);

INSERT INTO FACT_STORAGE_SNAPSHOT (SK_CAR, SK_STORAGE, SK_SNAPSHOT_DATE, DAYS_ON_STORAGE)
VALUES
(9, 2, 3, 20);

INSERT INTO FACT_STORAGE_SNAPSHOT (SK_CAR, SK_STORAGE, SK_SNAPSHOT_DATE, DAYS_ON_STORAGE)
VALUES
(10, 1, 4, 5);



------------------------------------------------------------------------
-- FACT SALES PIPELINE
INSERT INTO FACT_SALES_PIPELINE (SK_Car,SK_Client,SK_STORAGE,SK_MF_ORDER_DATE,SK_ST_DELIVERY_DATE,SK_CLIENT_ORDER_DATE,
SK_CLIENT_DELIVERY_DATE,MF_PRICE,DAYS_BTW_CLNT_ORDER_DLVRY)
values (8, 2, 3, '2021-09-19', '2021-10-19', '2022-04-22', '2022-04-30', 400, 8);

INSERT INTO FACT_SALES_PIPELINE (SK_Car,SK_Client,SK_STORAGE,SK_MF_ORDER_DATE,SK_ST_DELIVERY_DATE,SK_CLIENT_ORDER_DATE,
SK_CLIENT_DELIVERY_DATE,MF_PRICE,DAYS_BTW_CLNT_ORDER_DLVRY)
values (9, 4, 2, '2021-03-22', '2021-07-10', '2021-09-19', '2021-09-30', 340, 11);

INSERT INTO FACT_SALES_PIPELINE (SK_Car,SK_Client,SK_STORAGE,SK_MF_ORDER_DATE,SK_ST_DELIVERY_DATE,SK_CLIENT_ORDER_DATE,
SK_CLIENT_DELIVERY_DATE,MF_PRICE,DAYS_BTW_CLNT_ORDER_DLVRY)
values (10, 8, 1, '2021-10-19', '2022-02-04', '2022-05-10', '2022-05-30', 550, 20);
